"""
Training data for the NLP auto-categorization model.
300+ Indian merchant names covering common expense categories.
This is what makes the model actually work for Indian users —
generic models trained on US merchants fail on "Swiggy", "IRCTC", etc.
"""

TRAINING_DATA = [
    # ─── FOOD ───────────────────────────────────────────────────────────────
    ("Zomato", "Food"),
    ("Swiggy", "Food"),
    ("Blinkit", "Food"),
    ("Zepto", "Food"),
    ("Dunzo", "Food"),
    ("McDonald's", "Food"),
    ("KFC", "Food"),
    ("Domino's Pizza", "Food"),
    ("Pizza Hut", "Food"),
    ("Burger King", "Food"),
    ("Subway", "Food"),
    ("Starbucks", "Food"),
    ("Cafe Coffee Day", "Food"),
    ("Barista", "Food"),
    ("Haldiram's", "Food"),
    ("Barbeque Nation", "Food"),
    ("Saravana Bhavan", "Food"),
    ("Udupi Restaurant", "Food"),
    ("Darshini", "Food"),
    ("MTR Foods", "Food"),
    ("Natural Ice Cream", "Food"),
    ("Amul Parlour", "Food"),
    ("Baskin Robbins", "Food"),
    ("Chaayos", "Food"),
    ("Tea Point", "Food"),
    ("Chai Sutta Bar", "Food"),
    ("Biryani Blues", "Food"),
    ("Paradise Biryani", "Food"),
    ("Behrouz Biryani", "Food"),
    ("Box8", "Food"),
    ("Freshmenu", "Food"),
    ("EatFit", "Food"),
    ("Faasos", "Food"),
    ("Rebel Foods", "Food"),
    ("Licious", "Food"),
    ("FreshToHome", "Food"),
    ("BigBasket", "Food"),
    ("Grofers", "Food"),
    ("JioMart", "Food"),
    ("DMart", "Food"),
    ("More Supermarket", "Food"),
    ("Star Bazaar", "Food"),
    ("Reliance Fresh", "Food"),
    ("Spencer's", "Food"),
    ("Nature's Basket", "Food"),
    ("Nilgiris", "Food"),
    ("Foodpanda", "Food"),
    ("Fassos", "Food"),
    ("Oven Story", "Food"),

    # ─── TRANSPORT ──────────────────────────────────────────────────────────
    ("Ola", "Transport"),
    ("Uber", "Transport"),
    ("Rapido", "Transport"),
    ("InDrive", "Transport"),
    ("Meru Cabs", "Transport"),
    ("Indian Railways", "Transport"),
    ("IRCTC", "Transport"),
    ("RedBus", "Transport"),
    ("AbhiBus", "Transport"),
    ("MakeMyTrip Bus", "Transport"),
    ("KSRTC", "Transport"),
    ("BMTC", "Transport"),
    ("BEST Bus", "Transport"),
    ("DTC Bus", "Transport"),
    ("Metro Rail", "Transport"),
    ("Namma Metro", "Transport"),
    ("Delhi Metro", "Transport"),
    ("Mumbai Metro", "Transport"),
    ("Chennai Metro", "Transport"),
    ("Hyderabad Metro", "Transport"),
    ("Auto Rickshaw", "Transport"),
    ("Petrol Pump", "Transport"),
    ("HP Petrol", "Transport"),
    ("Indian Oil", "Transport"),
    ("BPCL", "Transport"),
    ("Shell Petrol", "Transport"),
    ("Reliance Petrol", "Transport"),
    ("FASTag", "Transport"),
    ("NHAI Toll", "Transport"),
    ("Parking Fee", "Transport"),
    ("Yulu", "Transport"),
    ("Bounce", "Transport"),
    ("Vogo", "Transport"),
    ("BluSmart", "Transport"),
    ("Ola Electric", "Transport"),
    ("Ather Energy", "Transport"),

    # ─── ENTERTAINMENT ──────────────────────────────────────────────────────
    ("BookMyShow", "Entertainment"),
    ("PVR Cinemas", "Entertainment"),
    ("INOX", "Entertainment"),
    ("Cinepolis", "Entertainment"),
    ("Carnival Cinemas", "Entertainment"),
    ("Netflix", "Entertainment"),
    ("Amazon Prime", "Entertainment"),
    ("Disney+ Hotstar", "Entertainment"),
    ("SonyLIV", "Entertainment"),
    ("Zee5", "Entertainment"),
    ("Voot", "Entertainment"),
    ("MX Player", "Entertainment"),
    ("ALTBalaji", "Entertainment"),
    ("Eros Now", "Entertainment"),
    ("JioCinema", "Entertainment"),
    ("Spotify", "Entertainment"),
    ("Gaana", "Entertainment"),
    ("JioSaavn", "Entertainment"),
    ("Wynk Music", "Entertainment"),
    ("Apple Music", "Entertainment"),
    ("YouTube Premium", "Entertainment"),
    ("Steam", "Entertainment"),
    ("PlayStation Store", "Entertainment"),
    ("Xbox Game Pass", "Entertainment"),
    ("Google Play Games", "Entertainment"),
    ("Dream11", "Entertainment"),
    ("MPL", "Entertainment"),
    ("WinZO", "Entertainment"),
    ("Paytm Games", "Entertainment"),
    ("Ludo King", "Entertainment"),
    ("Wonderla", "Entertainment"),
    ("EsselWorld", "Entertainment"),
    ("Imagica", "Entertainment"),

    # ─── SHOPPING ───────────────────────────────────────────────────────────
    ("Amazon", "Shopping"),
    ("Flipkart", "Shopping"),
    ("Myntra", "Shopping"),
    ("Ajio", "Shopping"),
    ("Nykaa", "Shopping"),
    ("Meesho", "Shopping"),
    ("Snapdeal", "Shopping"),
    ("Tata CLiQ", "Shopping"),
    ("Reliance Digital", "Shopping"),
    ("Croma", "Shopping"),
    ("Vijay Sales", "Shopping"),
    ("Sangeetha Mobiles", "Shopping"),
    ("Poorvika", "Shopping"),
    ("H&M", "Shopping"),
    ("Zara", "Shopping"),
    ("Westside", "Shopping"),
    ("Pantaloons", "Shopping"),
    ("Lifestyle", "Shopping"),
    ("Max Fashion", "Shopping"),
    ("FabIndia", "Shopping"),
    ("Fabindia", "Shopping"),
    ("W For Woman", "Shopping"),
    ("Biba", "Shopping"),
    ("Manyavar", "Shopping"),
    ("Van Heusen", "Shopping"),
    ("Allen Solly", "Shopping"),
    ("Louis Philippe", "Shopping"),
    ("Peter England", "Shopping"),
    ("Woodland", "Shopping"),
    ("Bata", "Shopping"),
    ("Puma", "Shopping"),
    ("Nike", "Shopping"),
    ("Adidas", "Shopping"),
    ("Decathlon", "Shopping"),
    ("Lenskart", "Shopping"),
    ("Clovia", "Shopping"),
    ("Bewakoof", "Shopping"),
    ("The Man Company", "Shopping"),
    ("Mamaearth", "Shopping"),
    ("WOW Skin Science", "Shopping"),

    # ─── UTILITIES ──────────────────────────────────────────────────────────
    ("BESCOM", "Utilities"),
    ("TNEB", "Utilities"),
    ("MSEDCL", "Utilities"),
    ("BSES", "Utilities"),
    ("Tata Power", "Utilities"),
    ("Adani Electricity", "Utilities"),
    ("CESC", "Utilities"),
    ("Electricity Bill", "Utilities"),
    ("Water Bill", "Utilities"),
    ("Gas Bill", "Utilities"),
    ("Indane Gas", "Utilities"),
    ("HP Gas", "Utilities"),
    ("Bharat Gas", "Utilities"),
    ("Piped Gas", "Utilities"),
    ("Mahanagar Gas", "Utilities"),
    ("Jio", "Utilities"),
    ("Airtel", "Utilities"),
    ("Vi Vodafone", "Utilities"),
    ("BSNL", "Utilities"),
    ("ACT Fibernet", "Utilities"),
    ("Hathway", "Utilities"),
    ("Tata Sky", "Utilities"),
    ("Dish TV", "Utilities"),
    ("Sun Direct", "Utilities"),
    ("Airtel DTH", "Utilities"),
    ("D2H", "Utilities"),
    ("Broadband Bill", "Utilities"),
    ("Mobile Recharge", "Utilities"),
    ("Postpaid Bill", "Utilities"),

    # ─── HEALTH ─────────────────────────────────────────────────────────────
    ("Apollo Pharmacy", "Health"),
    ("MedPlus", "Health"),
    ("Netmeds", "Health"),
    ("1mg", "Health"),
    ("PharmEasy", "Health"),
    ("Practo", "Health"),
    ("Apollo Hospitals", "Health"),
    ("Fortis Hospital", "Health"),
    ("Manipal Hospital", "Health"),
    ("Columbia Asia", "Health"),
    ("Max Healthcare", "Health"),
    ("Narayana Health", "Health"),
    ("Thyrocare", "Health"),
    ("Dr Lal PathLabs", "Health"),
    ("SRL Diagnostics", "Health"),
    ("Metropolis", "Health"),
    ("Healthkart", "Health"),
    ("Cult.fit", "Health"),
    ("Cure.fit", "Health"),
    ("Gold's Gym", "Health"),
    ("Anytime Fitness", "Health"),
    ("Talwalkars", "Health"),
    ("Yoga Studio", "Health"),
    ("Doctor Consultation", "Health"),
    ("Dental Clinic", "Health"),
    ("Eye Hospital", "Health"),
    ("Opticals", "Health"),
    ("Medical Store", "Health"),

    # ─── EDUCATION ──────────────────────────────────────────────────────────
    ("Coursera", "Education"),
    ("Udemy", "Education"),
    ("Unacademy", "Education"),
    ("BYJU'S", "Education"),
    ("Vedantu", "Education"),
    ("WhiteHat Jr", "Education"),
    ("upGrad", "Education"),
    ("Great Learning", "Education"),
    ("Simplilearn", "Education"),
    ("edX", "Education"),
    ("LinkedIn Learning", "Education"),
    ("Pluralsight", "Education"),
    ("Codecademy", "Education"),
    ("GeeksForGeeks", "Education"),
    ("InterviewBit", "Education"),
    ("LeetCode", "Education"),
    ("HackerRank", "Education"),
    ("Scaler", "Education"),
    ("Newton School", "Education"),
    ("Masai School", "Education"),
    ("School Fees", "Education"),
    ("College Fees", "Education"),
    ("Tuition Fees", "Education"),
    ("Books", "Education"),
    ("Stationery", "Education"),
    ("Khan Academy", "Education"),

    # ─── TRAVEL ─────────────────────────────────────────────────────────────
    ("MakeMyTrip", "Travel"),
    ("Goibibo", "Travel"),
    ("Yatra", "Travel"),
    ("Cleartrip", "Travel"),
    ("EaseMyTrip", "Travel"),
    ("ixigo", "Travel"),
    ("OYO", "Travel"),
    ("Treebo Hotels", "Travel"),
    ("FabHotels", "Travel"),
    ("Airbnb", "Travel"),
    ("Taj Hotels", "Travel"),
    ("ITC Hotels", "Travel"),
    ("Marriott", "Travel"),
    ("Hyatt", "Travel"),
    ("Hilton", "Travel"),
    ("IndiGo", "Travel"),
    ("Air India", "Travel"),
    ("SpiceJet", "Travel"),
    ("Vistara", "Travel"),
    ("GoAir", "Travel"),
    ("AirAsia India", "Travel"),
    ("Akasa Air", "Travel"),
    ("Emirates", "Travel"),
    ("Singapore Airlines", "Travel"),
    ("Visa Fees", "Travel"),
    ("Travel Insurance", "Travel"),
    ("Holiday Package", "Travel"),
    ("Thomas Cook", "Travel"),
    ("Cox and Kings", "Travel"),
]
